name: AI Code Reviewer
'on':
  push:
    branches:
      - master
  pull_request: null
jobs:
  code_review:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Collect Changed Files
        id: changed_files
        run: |
          if git rev-parse HEAD~1 >/dev/null 2>&1; then
            # Normal diff for subsequent commits
            files=$(git diff --name-only HEAD~1 HEAD)
          else
            # Diff from the root commit for the initial commit
            files=$(git diff --name-only --root HEAD)
          fi

          # Export the file list for later steps
          echo "files=$files" >> $GITHUB_ENV
      - name: Run AI Code Reviewer
        env:
          BACKEND_URL: 'http://10.241.220.147:5001/review'
        run: |
          # Loop through changed files and send each to the AI reviewer
          for file in ${{ env.files }}; do
            if [[ $file == *.py || $file == *.js ]]; then
              echo "Reviewing $file..."
              content=$(cat "$file" | jq -Rs .) # Escape JSON
              response=$(curl -s -X POST $BACKEND_URL -H "Content-Type: application/json" -d "{\"code\": $content}")
              echo "AI Suggestions for $file:"
              echo $response
            else
              echo "Skipping non-code file: $file"
            fi
          done
